document.write("Hello everyone! This is an external JS file.<br>")
document.write(2022)
document.write("<br>")
document.write("The value of 4+4 is "+(4+4))
document.write("<br>")
document.write("2"+"4"+"<br>")
document.write(2,4)
document.write("<br>")
document.write("<br>")
document.write("<br>")